A.PROJECT-3/CameraShop/Quickclick/Cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "Cart"

urlpatterns = [
    path("",views.cart_detail, name= "cart_detail"),
    path("add/<int:product_id>", views.cart_add, name = "cart_add"),
    path('remove/<slug:obj_product>/<int:product_id>/', views.cart_remove, name='cart_remove'),
    
]

A.PROJECT-3/CameraShop/Quickclick/Main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "Main"

urlpatterns = [
    
    path("", views.Main, name="Main"), 
    path("Camers/", views.Camers, name="Camers"),
    path(r"^C_filtred/", views.Camers_filtred, name="Camers_filtred"),
    path("Filtred_Camers/", views.Camers_filtred, name="Camers_Filtred"),
    path("Lens/", views.Lens, name="Lens"),
    path(r"^L_filtred/", views.Lens_filtred, name="Lens_filtred"),
    path("Lightings/", views.Lighting, name="Lightings"),
    path("Tripods/", views.Tripods, name="Tripods"),
    path("binoculars/", views.binoculars, name="binoculars"),
    path("Camers/<str:cam_id>/<slug:obj_product>/", views.Camera_product, name="Camers_product"),
    path("Lens/<str:lens_id>/<slug:obj_product>/", views.Lens_product, name="Lens_product"),
    path("Tripods/<str:trip_id>/<slug:obj_product>/", views.Tripods_product, name="Tripods_product"),
    path("Lightings/<str:Lighting_id>/<slug:obj_product>/", views.Lighting_product, name="Lightings_product"),
    path("binoculars/<str:Binoculars_id>/<slug:obj_product>/", views.Binoculars_product, name="binoculars_product"),
    path("Profile/", views.Profile_Page, name = "Profile"),
    path(r'^authentication/', views.authentication, name='authentication'),
    path("Change_process/", views.Change_Profile_Name, name = "Change_Name"),
    path("Change_process-2/", views.Change_Profile_Last, name = "Change_Last"),
    path("Change_process-3/", views.Change_Profile_Email, name = "Change_Email"),
    path("Change_process-4/", views.Change_Profile_Foto, name = "Change_Foto"),
    path("ErrorNoGetData", views.ErrorGetData, name="ErrorGetData"),
    path('AboutUs/', views.AboutUs, name='AboutUs'),
    path(r'^SearchAll/', views.SearchAll, name='SearchAll'),
    
    path('logout/', views.logout_view, name='logout'),
    
    # Home Page
]
#url(r'^result/(?P<result>[^\/]*)/$', views.result, name='result'),

A.PROJECT-3/CameraShop/Quickclick/orders/urls.py
from django.urls import path 
from . import views

app_name ="orders"

urlpatterns = [
    path("created", views.order_create, name="order_create")
]

A.PROJECT-3/CameraShop/Quickclick/users/urls.py
from django.urls import path, include
from . import views

app_name= "users"

urlpatterns = [
    path("",include('django.contrib.auth.urls')),
    path("/registration",views.register, name="register")
]

A.PROJECT-3/CameraShop/Quickclick/Main/forms.py
from django import forms

from .models import PROFILE_IMG


class IMG_PROFILE_FORM(forms.ModelForm):
    class Meta:
        model = PROFILE_IMG
        fields = ["image", "post"]
        labels = {"image": " "}
        
        widgets = {'post': forms.HiddenInput()}
        

A.PROJECT-3/CameraShop/Quickclick/Main/views.py
from mixer.backend.django import mixer
from django.contrib.auth.models import User
import ast
user = mixer.blend(User)
from .superclass import Contener
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import IMG_PROFILE_FORM
from .models import Color,Category,Camera, lens, lightings, tripods, Binoculars, IMG_FILES, IMG_FILES_LENS, IMG_FILES_TRIPODS, IMG_FILES_LIGHTS, IMG_FILES_BINOCULARS, account_data, PROFILE_IMG
from django.db import connection
from .superclass import Contener
from Cart.forms import CartAddProductsForm
from Cart.Cart import Cart
from .Contaner import Contener_SCSS_to_CSS
import os

from django.http import QueryDict
# Create your views here.
from django.contrib import messages
import pathlib
from django.contrib.auth import authenticate, login, logout
import shutil

from django.conf import settings

FORM_FLAG = False
CONTENT_FLAG = False
COUNT = 0

def authentication(request):
    
    __login = request.GET.get('login')
    __password = request.GET.get('password')
    user = authenticate(request, username=__login, password=__password)
    if user is not None:
        login(request, user)
        
        return redirect(request.META.get('HTTP_REFERER','redirect_if_referer_not_found'))
    else:
        global CONTENT_FLAG
        CONTENT_FLAG = True
        count = 0
        #http://127.0.0.1:8000/Lightings/
        l=[]
        str_class = []
        #'http://127.0.0.1:8000/Camers/'
        for x in request.META['HTTP_REFERER']:
            
            if x == "/":
                count +=1
                continue
            if count == 3:
                l.extend(x)  
            if count == 4:
                arg = x
            if count == 5:
                str_class.extend(x)
        
        str_class = "".join(str_class) 
        html_name= "".join(l)
        if count > 4:
            html_name += "_product"
        if html_name == "":
            html_name= "Main"
            
        
        try:
            # ЕСЛИ ЕСТЬ АРГУМЕНТЫ
            content = (arg,str_class)
            print(html_name)
            print(str_class)
            redirect_url = reverse(f"Main:{html_name}", args=content)
            return redirect(f'{redirect_url}')
        except:
            # НЕТ АРГУМЕНТОВ
            return redirect(f"Main:{html_name}")

def UserLoggedIn(request):
    if request.user.is_authenticated == True:
        username = request.user.username
    else:
        username = None
    return username

def logout_view(request):
    username = UserLoggedIn(request)
    if username != None:
        logout(request)
        return redirect("Main:Main")

def Main(request):
    content = {}
    global CONTENT_FLAG
    if CONTENT_FLAG == True:
        content['some_flag'] = True
        CONTENT_FLAG = False
    return render(request, "Main/URLS/Main.html", content)

def Camers(request):
    product = Camera.objects.all()
    line = (len(product.values())//4+1)
    if len(product.values()) % 4 == 0:
        line = line -1
    cart_product_form = CartAddProductsForm(pquant=1)
    category_camera = {" ": ""}
    category_camera_spec = {" ": ""}
    category_matrix_format = {" ": ""}
    category_Bayonet = {" ": ""}
    category_Color = {" ": ""}
    for i in product:
        category_camera[i.category]= ""
        category_camera_spec[i.firm] = ""
        category_matrix_format[i.Matrix_format] = ""
        category_Bayonet[i.Bayonet] = ""
        category_Color[i.color] = ""
    
    
   
    quant = []
    cart_product_form = []
    for elem in product:    
        if elem.stock < 21:
            pquant = elem.stock + 1
        
            cart_product_form.append(CartAddProductsForm(pquant=pquant))
        else:
            pquant = 21
            cart_product_form.append(CartAddProductsForm())
        
 

        quant.append(Cart(request).productq(str(elem.id), elem.klass()))
    if product == []:
            mylist = False
    else:
        mylist = zip(product, cart_product_form)
    content = {"Camers":mylist, 
               "line": 440* line,
               'len_prod': len(product),
               "quant": quant,
               "category_camera": category_camera.keys(),
               "category_camera_spec": category_camera_spec.keys(), 
               "category_matrix_format": category_matrix_format.keys(),
               "category_Bayonet": category_Bayonet.keys(),
               "category_Color": category_Color.keys()
               }
    global CONTENT_FLAG
    if CONTENT_FLAG == True:
        content['some_flag'] = True
        CONTENT_FLAG = False
        
    return render(request, "Main/URLS/Camers.html", content )
  
def Camers_filtred(request):
    global CONTENT_FLAG
    ID_CAMERA = request.GET.get('ID-CAMERA')
    ID_CAMERA_SPEC = request.GET.get('ID-CAMERA-SPEC')
    ID_MATRIX_FORMAT = request.GET.get("ID-MATRIX_FORMAT")
    ID_BAYONET = request.GET.get("ID-BAYONET")
    ID_COLOR = request.GET.get("ID-COLOR")
    ID_BUDJET = request.GET.get("pi_input")
    ID_LENS = request.GET.get("ID-LENS")
    ID_HAND = request.GET.get("ID-HAND")
    if ID_LENS == "false":
        ID_LENS = False
    else:
        ID_LENS = True 
    if ID_HAND == "false":
        ID_HAND = False
    else:
        ID_HAND = True
    try:
        category = Category.objects.values().filter(model= ID_CAMERA)[0]["id"]
        selected_category = True
    except:
        category = None
    try:
        color = Color.objects.values().filter(color= ID_COLOR)[0]["id"]
        selected_color= True
    except:
        color = None
            
    product_1 = Camera.objects.filter(category= category)
    product_2 = Camera.objects.filter(firm= ID_CAMERA_SPEC)
    product_3 = Camera.objects.filter(Matrix_format= ID_MATRIX_FORMAT)
    product_4 = Camera.objects.filter(Bayonet= ID_BAYONET)
    product_5 = Camera.objects.filter(color= color)
    product_6 = Camera.objects.filter(lens= ID_LENS)
    product_7 = Camera.objects.filter(hand= ID_HAND)
    list_product = [product_1,product_2,product_4,product_3,product_5, product_6, product_7]
    result = []
    len_objest = 4
    last_step = True
    first = True
    ex_list = []
    RESULT_LIST_ID = []
    for index in range(len(list_product)):
        if str(list_product[index]) == "<QuerySet []>":
            len_objest -=1
            last_step = False
        else:
            if last_step== True:
                last_step_list = list_product[index]
                ex_list.append(last_step_list)
            else:
                try:
                    for elem in last_step_list:
                        if elem in list_product[index]:
                                RESULT_LIST_ID.append(elem) # тут
                                first = False
                        last_step = True
                    if first == False:
                        res= list(set(RESULT_LIST_ID) & set(list_product[index+1]))
                        RESULT_LIST_ID.clear()
                        first = True
                except:
                    res = product_5  

    try:
        if last_step == False and len_objest == 0 and selected_category: # ПРОВЕРКА ЕСЛИ ТОЛЬКО ВЫБРАНА КАТЕГОРИЯ 

            
            for elem in product_1:
                RESULT_LIST_ID.append(elem)
    except:
        pass
    try:
        if last_step == True and len_objest == 0 and selected_color: # ПРОВЕРКА ЕСЛИ ТОЛЬКО ВЫБРАНА КАТЕГОРИЯ 

            
            for elem in product_5:
                RESULT_LIST_ID.append(elem)
    except:
        pass
    
    res_end = []
    first = True   
    try:
        if last_step == False and len_objest == 0 and selected_color: # ПРОВЕРКА ЕСЛИ ТОЛЬКО ВЫБРАН ЦВЕТ
            for elem in product_5:
                RESULT_LIST_ID.append(elem)
    except:
        pass
  
    try:
        res
    except:
        for index in range(len(ex_list)):
            try:
                if first:
                    first = False
                    res_end.extend(list(set(ex_list[index]) & set(ex_list[index+1])))
                if first == False:
                    res = list(set(res_end[::-1]) & set(ex_list[index+1]))
                    print(res)
                    first = True
                if res == []:
                    break
            except:
                pass
    c = 0
    
    
    if last_step == True and str(list_product[-2]) == "<QuerySet []>":
        while True:
            c+=1
            if str(list_product[-2-c]) != "<QuerySet []>":
                res =list(set(list_product[-2-c]) & set(RESULT_LIST_ID))
                break

    try:  
        result = []
        for elem in res:
            if int(elem.price) <= int(ID_BUDJET):
                result.append(elem)
        line = (len(result)//4+1)
        if len(result) % 4 == 0:
            line = line -1
        cart_product_form = CartAddProductsForm(pquant=1)
        category_camera = {" ": ""}
        category_camera_spec = {" ": ""}
        category_matrix_format = {" ": ""}
        category_Bayonet = {" ": ""}
        category_Color = {" ": ""}
        for i in Camera.objects.all():
            category_camera[i.category]= ""
            category_camera_spec[i.firm] = ""
            category_matrix_format[i.Matrix_format] = ""
            category_Bayonet[i.Bayonet] = ""
            category_Color[i.color] = ""
        
        if result == []:
            result = True
            
            
        quant = []
        cart_product_form = []
        for elem in result:    
            if elem.stock < 21:
                pquant = elem.stock + 1
            
                cart_product_form.append(CartAddProductsForm(pquant=pquant))
            else:
                pquant = 21
                cart_product_form.append(CartAddProductsForm())
            quant.append(Cart(request).productq(str(elem.id), elem.klass()))
        if result == []:
            mylist = False
        else:

A.PROJECT-3/CameraShop/Quickclick/Main/templates/Main/URLS/Change_Profile_Data.html
{% extends "Main/base.html" %}
{% block content %}

{%load static%}

{% endblock content %}

A.PROJECT-3/CameraShop/Quickclick/Main/templates/Main/URLS/Lens.html
{% extends "Main/base.html" %}





{% block content %}
{%load tegs_page%}

{% if some_flag %}
<meta http-equiv="refresh" content="0; #popup" />
{%endif%}


{%load static%}

{% for l, form in Lens %}
    <div class = "block-product">
        <div class = "description-product-block">

            <a href="{{l.get_absolute_url}}"><img src={{l.image.url}} height="170" style="max-width: 150px"></a>
            <div class = "description-text-product" >
            </div>
            <div class= "buttons-buy-info-pr">
                <div>Name: {%if l.name|length > 16 %} {{l.name|slice:"0:16"}}...{%else %}{{l.name}}{%endif%} 
                </div>
                <div>Category: {{l.category}}</div>

                <div>Type: {{l.type}}</div>
                <div> Hand: {%if l.hand%} Usefull {%else%} Original {%endif%}</div>

                <div>Date of publication: {{l.created}}</div>
                <div>Color: {{l.color}}</div>
                
                
            </div>
        </div>
    <div class = 'copyright'>                     
        {% if request.user.is_authenticated %}
            <form action="{% url 'Cart:cart_add' l.id %}" method='post' >
                    {% csrf_token %}
                    {{ form }}
                    <div class= "buttons-buy-info-pr-2">
                    <div class= "pr-price" >Price: {{l.price}}$</div>
                    </div>
                    <div class="buy-logo"><button name="submit" ><h3> Into a basket </h3></button></div>
                </form>
        {% else %}
            <div class= "pr-price" >Price: {{l.price}}$</div>
            <div class="buy-logo"><button name="submit" ><h3><a href= "#popup-2">Into a basket</a></h3></button></div>
        {% endif %}
        <div class="info-logo-pr"><button><h3><a href="{% url "Main:Lens_product" l.id l.klass %}">Info</a></h3></button></div> </div>
    </div>
    
{% endfor %}

<div class="m" id = 'elemID1' data-myvariable = "{{len_prod}}" > <!-- ТАКИМ ОБРАЗОМ МОЖНО ПЕРЕДАТЬ АРГУМЕНТ В CSS ПОЖАЛУЙСТА ЗАПОМНИТЬ!-->
</div>


<script>
    var RowContentWidthFir = document.getElementById('Content_id').clientWidth
    if (RowContentWidthFir == '915' ){
        var ElementSizeFir = '880' 
    }
    if (RowContentWidthFir == '815' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '740' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '660' ){
        var ElementSizeFir = '440' 
    }
    if (RowContentWidthFir == '430' ){
        var ElementSizeFir = '220' 
    }
    var MyVariableFir = document.getElementById('elemID1').getAttribute("data-myvariable");
        var LinesInRowFir =  Math.ceil(MyVariableFir * 220 / ElementSizeFir) * 440
        let outputFir = document.getElementById('elemID1');
        let resFir = "--m";
        let valueFir = LinesInRowFir.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        outputFir.style.setProperty(resFir, valueFir);
</script>
<script>
    window.addEventListener('resize', function() {
        var RowContentWidth = document.getElementById('Content_id').clientWidth
        if (RowContentWidth == '915' ){
            var ElementSize = '880' 
        }
        if (RowContentWidth == '815' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '740' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '660' ){
            var ElementSize = '440' 
        }
        if (RowContentWidth == '430' ){
            var ElementSize = '220' 
        }
        var MyVariable = document.getElementById('elemID1').getAttribute("data-myvariable");
        var LinesInRow =  Math.ceil(MyVariable * 220 / ElementSize) * 440
        let output = document.getElementById('elemID1');
        let resss = "--m";
        let value131 = LinesInRow.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        output.style.setProperty(resss, value131);
    });
</script>




{% endblock content %}


{% block left-content-ctg %}
<div class = "content-ctg">
    <div class= "label-categ-head">
        <h1>Category</h1>
    </div>
    
    <div class = "form-category">
        <div class = "price-category">
            <p class = "label-ctg" >Budget: <output id="value"></output>$</p>
            <input id="pi_input" type="range" value= "7500" class = "miksher" min="0" max="15000" step="100" />
            <script>
                const value = document.querySelector("#value");
                const input = document.querySelector("#pi_input");
                value.textContent = input.value;
                input.addEventListener("input", (event) => {
                value.textContent = event.target.value;
                });</script>
        </div>

        <div class = "select-box">
            
            <div class = "having-some">
                <p class = "label-ctg-2" >Second-hand:</p>
                <input id= "ID-HAND" type="checkbox">
            </div>
        </div>
        <div class = "list-ctg">
            
            <div class = "select-ctg">
                <p class = "label-ctg" >Company:</p>
               
                <form name="myForm">
                    
                    <select id = "ID-CAMERA" name="language" class = "select-windows">
                        {% with True as flag %}
                            {% for c in category_obj_camera %}
                                {% if flag %}
                                    <option style="display:none;" value="{{ c }}">Select</option>
                                    {% update_variable False as flag %}
                                {%else%}
                                    <option value="{{ c }}">{{ c }}</option>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    </select>
                </form>
                
                
                
                
                <!-- Достать аргумент по клику затем создать событие связывающие этот аргумент с другими элементами следующего списка -->
            </div>
            <div class = "select-ctg">
                <p class = "label-ctg" >Type:</p>
                
                <div id="blockspec" name = "blockspec">
                    <select id = "ID-CAMERA-SPEC" name = "lens-camera-spec" class = "select-windows"атрибуты>
                        {% with True as flag %}
                            {% for c in category_type %}
                                {% if flag %}
                                    <option style="display:none;" id="selection" value="{{ c }}">Select</option>
                                    {% update_variable False as flag %}
                                {%else%}
                                    <option id="selection" value="{{ c }}">{{ c }}</option>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                        </div>
                    </select> 
                </div>
               
            </div>
            <div class = "select-ctg">
                <div id="blockspec" name = "blockspec">
                    <p class = "label-ctg" >Color:</p>
                    <select id = "ID-BAYONET" name = "bayonet-camera" class = "select-windows"атрибуты>
                        {% with True as flag %}
                            {% for c in category_Color %}
                                
                                {% if flag %}
                                
                                    <option style="display:none;" id="selection2" value="{{ c }}">Select</option>
                                    {% update_variable False as flag %}
                                
                                {%else%}
                                    <option id="selection2" value="{{ c }}">{{ c }}</option>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    </select> 
                </div>
            </div>
            
            
            
            
            
            <div class= "Change-button-2">
                <button class = "log-button-acc" onClick="submit()">Change</button>
            </div>
            <script>
                function submit(){
                    var a = document.getElementById("ID-CAMERA").value;
                    var b = document.getElementById("ID-CAMERA-SPEC").value;
                    var d = document.getElementById("ID-BAYONET").value;
                    
                    var budjet = document.getElementById("pi_input").value;
                    
                    var isHend = document.getElementById('ID-HAND').checked; 
                    
                    window.location.href = "{% url 'Main:Lens_filtred' %}" + 
                    "?category_obj_camera="+ a +
                    "&category_type=" + 
                    b +"&category_Color=" + 
                    d +"&pi_input="+
                    budjet + "&ID-HAND=" + 
                    isHend
                    
                    ; 
                }
            </script>
        </div>
        



    </div>
</div>


{% endblock left-content-ctg %}

A.PROJECT-3/CameraShop/Quickclick/Main/templates/Main/URLS/Lightings.html
{% extends "Main/base.html" %}





{% block content %}

{% if some_flag %}
<meta http-equiv="refresh" content="0; #popup" />
{%endif%}

{%load static%}

{% for l in Lightings %}
    <div class = "block-product">
        <div class = "description-product-block">

            <a href="{{l.get_absolute_url}}"><img src={{l.image.url}} height="170" style="max-width: 150px"></a>
            <div class = "description-text-product" >
                <div class= "buttons-buy-info-pr">
                <div>Name: {%if l.name|length > 16 %} {{l.name|slice:"0:16"}}...{%else %}{{l.name}}{%endif%}</div>
                <div>Supports {{l.power}} charging</div>
                <div>Charging time: {{l.time_power}}</div>
                <div>Date of publication: {{l.created}}</div>
                </div>
            </div>
        </div>
                
        <div class = 'copyright'>

            <div class= "pr-price" >Price: {{l.price}}$</div>
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'Cart:cart_add' l.id %}" method='post' >
                            {% csrf_token %}
                            {{ FORM_TO_BACKET }}
                            <div class="buy-logo"><button name="submit" ><h3> Into a basket </h3></button></div>
                        </form>
                    {%else%}
                        <div class="buy-logo"><button name="submit" ><h3><a href= "#popup-2">Into a basket</a></h3></button></div>
                    {% endif %}
                    <div class="info-logo-pr"><button type="submit"><h3><a href="{% url "Main:Lightings_product" l.id l.klass %}"> Info</a></h3></button></div>


        </div>
    </div>
    
{% endfor %}


<div class="m" id = 'elemID' data-myvariable = "{{len_prod}}" > <!-- ТАКИМ ОБРАЗОМ МОЖНО ПЕРЕДАТЬ АРГУМЕНТ В CSS ПОЖАЛУЙСТА ЗАПОМНИТЬ!-->
</div>


<script>
    var RowContentWidthFir = document.getElementById('Content_id').clientWidth
    if (RowContentWidthFir == '915' ){
        var ElementSizeFir = '880' 
    }
    if (RowContentWidthFir == '815' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '740' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '660' ){
        var ElementSizeFir = '440' 
    }
    if (RowContentWidthFir == '430' ){
        var ElementSizeFir = '220' 
    }
    var MyVariableFir = document.getElementById('elemID').getAttribute("data-myvariable");
        var LinesInRowFir =  Math.ceil(MyVariableFir * 220 / ElementSizeFir) * 440
        let outputFir = document.getElementById('elemID');
        let resFir = "--m";
        let valueFir = LinesInRowFir.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        outputFir.style.setProperty(resFir, valueFir);
</script>
<script>
    window.addEventListener('resize', function() {
        var RowContentWidth = document.getElementById('Content_id').clientWidth
        if (RowContentWidth == '915' ){
            var ElementSize = '880' 
        }
        if (RowContentWidth == '815' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '740' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '660' ){
            var ElementSize = '440' 
        }
        if (RowContentWidth == '430' ){
            var ElementSize = '220' 
        }
        var MyVariable = document.getElementById('elemID').getAttribute("data-myvariable");
        var LinesInRow =  Math.ceil(MyVariable * 220 / ElementSize) * 440
        let output = document.getElementById('elemID');
        let resss = "--m";
        let value131 = LinesInRow.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        output.style.setProperty(resss, value131);
    });
</script>

{% endblock content %}
{% block left-content-ctg %}
<div class= "label-categ-head">
    <h1>Category</h1>
</div>
<div class ="block-label-select-category">
  <div class= "Select-category"> There are no categories in this section </div>
</div>
{% endblock left-content-ctg %}

A.PROJECT-3/CameraShop/Quickclick/Main/templates/Main/URLS/Tripods.html
{% extends "Main/base.html" %}

{% block content %}


{% if some_flag %}
<meta http-equiv="refresh" content="0; #popup" />
{%endif%}


{%load static%}

{% for T in Tripods %}
    <div class = "block-product">
        <div class = "description-product-block">

            <a href="{{T.get_absolute_url}}"><img src={{T.image.url}} height="170" style="max-width: 150px"></a>
            <div class = "description-text-product" >
                <div>Name: {%if T.name|length > 16 %} {{T.name|slice:"0:16"}}...{%else %}{{T.name}}{%endif%} </div>
                <div class= "buttons-buy-info-pr">
                </div>
                <div> Color: {{T.color}}
                <div>Date of publication: {{T.created}}</div>
                </div>
            </div>
        </div>
        <div class="copyright" >
            <div class= "pr-price" >Price: {{T.price}}$</div>
            {% if request.user.is_authenticated %}
                <form action="{% url 'Cart:cart_add' T.id %}" method='post' >
                    {% csrf_token %}
                    {{ FORM_TO_BACKET }}
                    <div class="buy-logo"><button name="submit" ><h3> Into a basket </h3></button></div>
                </form>
            {%else%}
                <div class="buy-logo"><button name="submit" ><h3><a href= "#popup-2">Into a basket</a></h3></button></div>
            {% endif %}

            <div class="info-logo-pr"><button type="submit"><h3><a href="{% url "Main:Tripods_product" T.id T.klass %}"> Info</a></h3></button></div>
    
    </div>
    </div>
    
{% endfor %}


<div class="m" id = 'elemID' data-myvariable = "{{len_prod}}" > <!-- ТАКИМ ОБРАЗОМ МОЖНО ПЕРЕДАТЬ АРГУМЕНТ В CSS ПОЖАЛУЙСТА ЗАПОМНИТЬ!-->
</div>


<script>
    var RowContentWidthFir = document.getElementById('Content_id').clientWidth
    if (RowContentWidthFir == '915' ){
        var ElementSizeFir = '880' 
    }
    if (RowContentWidthFir == '815' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '740' ){
        var ElementSizeFir = '660' 
    }
    if (RowContentWidthFir == '660' ){
        var ElementSizeFir = '440' 
    }
    if (RowContentWidthFir == '430' ){
        var ElementSizeFir = '220' 
    }
    var MyVariableFir = document.getElementById('elemID').getAttribute("data-myvariable");
        var LinesInRowFir =  Math.ceil(MyVariableFir * 220 / ElementSizeFir) * 440
        let outputFir = document.getElementById('elemID');
        let resFir = "--m";
        let valueFir = LinesInRowFir.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        outputFir.style.setProperty(resFir, valueFir);
</script>
<script>
    window.addEventListener('resize', function() {
        var RowContentWidth = document.getElementById('Content_id').clientWidth
        if (RowContentWidth == '915' ){
            var ElementSize = '880' 
        }
        if (RowContentWidth == '815' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '740' ){
            var ElementSize = '660' 
        }
        if (RowContentWidth == '660' ){
            var ElementSize = '440' 
        }
        if (RowContentWidth == '430' ){
            var ElementSize = '220' 
        }
        var MyVariable = document.getElementById('elemID').getAttribute("data-myvariable");
        var LinesInRow =  Math.ceil(MyVariable * 220 / ElementSize) * 440
        let output = document.getElementById('elemID');
        let resss = "--m";
        let value131 = LinesInRow.toString() + "px"; // добавляем "px", чтобы указать единицы измерения
        output.style.setProperty(resss, value131);
    });
</script>


{% endblock content %}
{% block left-content-ctg %}
<div class= "label-categ-head">
    <h1>Category</h1>
</div>
<div class ="block-label-select-category">
  <div class= "Select-category"> There are no categories in this section </div>
</div>
{% endblock left-content-ctg %}