project_site/SnapBox/Cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "Cart"

urlpatterns = [
    path("",views.cart_detail, name= "cart_detail"),
    path("add/<int:product_id>", views.cart_add, name = "cart_add"),
    
]

project_site/SnapBox/Main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "Main"

urlpatterns = [
    
    path("", views.Main, name="Main"), 
    path("Camers/", views.Camers, name="Camers"),
    path(r"^C_filtred/", views.Camers_filtred, name="Camers_filtred"),
    path("Filtred_Camers/", views.Camers_filtred, name="Camers_Filtred"),
    path("Lens/", views.Lens, name="Lens"),
    path("Lightings/", views.Lighting, name="Lightings"),
    path("Tripods/", views.Tripods, name="Tripods"),
    path("binoculars/", views.binoculars, name="binoculars"),
    path("Camers/<str:cam_id>/<slug:obj_product>/", views.Camera_product, name="Camers_product"),
    path("Lens/<str:lens_id>/<slug:obj_product>/", views.Lens_product, name="Lens_product"),
    path("Tripods/<str:trip_id>/<slug:obj_product>/", views.Tripods_product, name="Tripods_product"),
    path("Lightings/<str:Lighting_id>/<slug:obj_product>/", views.Lighting_product, name="Lightings_product"),

    path("binoculars/<str:Binoculars_id>/<slug:obj_product>/", views.Binoculars_product, name="binoculars_product"),
    
    path(r'^authentication/', views.authentication, name='authentication'),
    path('logout/', views.logout_view, name='logout')
    # Home Page
]
#url(r'^result/(?P<result>[^\/]*)/$', views.result, name='result'),

project_site/SnapBox/SnapBox/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Main.urls")),
    path("/users", include("users.urls")),
    path("/Cart", include("Cart.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_site/SnapBox/Main/views.py
from mixer.backend.django import mixer
from django.contrib.auth.models import User

user = mixer.blend(User)

from pprint import pprint
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import RequestContext
from django.urls import reverse
from .models import Category,Camera, lens, lightings, tripods, Binoculars, IMG_FILES, IMG_FILES_LENS, IMG_FILES_TRIPODS, IMG_FILES_LIGHTS, IMG_FILES_BINOCULARS, account_data
from django.db import connection
from .superclass import Contener
from Cart.forms import CartAddProductsForm
from Cart.Cart import Cart
from .Contaner import Contener_SCSS_to_CSS
import os
# Create your views here.
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout

##############################################################################################################
#ДОББББББББББББББББББАВИТЬ КОЛИЧЕСТВО!!!!!!!!!!!!!
##############################################################################################################
##############################################################################################################
##############################################################################################################
##############################################################################################################

CONTENT_FLAG = False

    
def authentication(request):
    __login = request.GET.get('login')
    __password = request.GET.get('password')
    user = authenticate(request, username=__login, password=__password)
    if user is not None:
        login(request, user)
        
        return redirect(request.META.get('HTTP_REFERER','redirect_if_referer_not_found'))
    else:
        global CONTENT_FLAG
        CONTENT_FLAG = True
        count = 0
        #http://127.0.0.1:8000/Lightings/
        l=[]
        str_class = []
        #'http://127.0.0.1:8000/Camers/'
        for x in request.META['HTTP_REFERER']:
            
            if x == "/":
                count +=1
                continue
            if count == 3:
                l.extend(x)  
            if count == 4:
                arg = x
            if count == 5:
                str_class.extend(x)
        
        str_class = "".join(str_class) 
        html_name= "".join(l)
        if count > 4:
            html_name += "_product"
        if html_name == "":
            html_name= "Main"
            
        
        try:
            # ЕСЛИ ЕСТЬ АРГУМЕНТЫ
            content = (arg,str_class)
            print(html_name)
            print(str_class)
            redirect_url = reverse(f"Main:{html_name}", args=content)
            return redirect(f'{redirect_url}')
        except:
            # НЕТ АРГУМЕНТОВ
            return redirect(f"Main:{html_name}")

def UserLoggedIn(request):
    if request.user.is_authenticated == True:
        username = request.user.username
    else:
        username = None
    return username

def logout_view(request):
    username = UserLoggedIn(request)
    if username != None:
        logout(request)
        return redirect("Main:Main")


def Main(request):
    content = {}
    global CONTENT_FLAG
    if CONTENT_FLAG == True:
        content['some_flag'] = True
        CONTENT_FLAG = False
    return render(request, "Main/URLS/Main.html", content)



def Camers(request):
    product = Camera.objects.all()
    line = (len(product.values())//4+1)
    if len(product.values()) % 4 == 0:
        line = line -1
    cart_product_form = CartAddProductsForm(pquant=1)
    category_camera = {" ": ""}
    category_camera_spec = {" ": ""}
    category_matrix_format = {" ": ""}
    category_Bayonet = {" ": ""}
    category_Color = {" ": ""}
    for i in product:
        category_camera[i.category]= ""
        category_camera_spec[i.firm] = ""
        category_matrix_format[i.Matrix_format] = ""
        category_Bayonet[i.Bayonet] = ""
        category_Color[i.color] = ""
    content = {"Camers":product, 
               "line": 426* line,
               "FORM_TO_BACKET":cart_product_form,
               "category_camera": category_camera.keys(),
               "category_camera_spec": category_camera_spec.keys(), 
               "category_matrix_format": category_matrix_format.keys(),
               "category_Bayonet": category_Bayonet.keys(),
               "category_Color": category_Color.keys()
               }
    global CONTENT_FLAG
    if CONTENT_FLAG == True:
        content['some_flag'] = True
        CONTENT_FLAG = False
    return render(request, "Main/URLS/Camers.html", content )
    
    
def Camers_filtred(request):
    global CONTENT_FLAG
    ID_CAMERA = request.GET.get('ID-CAMERA')
    ID_CAMERA_SPEC = request.GET.get('ID-CAMERA-SPEC')
    ID_MATRIX_FORMAT = request.GET.get("ID-MATRIX_FORMAT")
    ID_BAYONET = request.GET.get("ID-BAYONET")
    ID_COLOR = request.GET.get("ID-COLOR")
    ID_BUDJET = request.GET.get("pi_input")
    ID_LENS = request.GET.get("ID-LENS")
    ID_HAND = request.GET.get("ID-HAND")
    if ID_LENS == "false":
        ID_LENS = False
    else:
        ID_LENS = True 
    if ID_HAND == "false":
        ID_HAND = False
    else:
        ID_HAND = True
    try:
        category = Category.objects.values().filter(model= ID_CAMERA)[0]["id"]
        selected_category = True
    except:
        category = None
    product_1 = Camera.objects.filter(category= category)
    product_2 = Camera.objects.filter(firm= ID_CAMERA_SPEC)
    product_3 = Camera.objects.filter(Matrix_format= ID_MATRIX_FORMAT)
    product_4 = Camera.objects.filter(Bayonet= ID_BAYONET)
    product_5 = Camera.objects.filter(color= ID_COLOR)
    product_6 = Camera.objects.filter(lens= ID_LENS)
    product_7 = Camera.objects.filter(hand= ID_HAND)
    
    list_product = [product_1,product_2,product_4,product_3,product_5, product_6, product_7]
    result = []
    len_objest = 4
    last_step = True
    first = True
    ex_list = []
    RESULT_LIST_ID = []
    for index in range(len(list_product)):
        if str(list_product[index]) == "<QuerySet []>":
            len_objest -=1
            last_step = False
        else:
            if last_step== True:
                last_step_list = list_product[index]
                ex_list.append(last_step_list)
            else:
                try:
                    for elem in last_step_list:
                        if elem in list_product[index]:
                                RESULT_LIST_ID.append(elem) # тут
                                first = False
                        last_step = True
                    if first == False:
                        res= list(set(RESULT_LIST_ID) & set(list_product[index+1]))
                        RESULT_LIST_ID.clear()
                        first = True
                except:
                    res = product_5  
    try:
        if last_step == False and len_objest == 0 and selected_category: # ПРОВЕРКА ЕСЛИ ТОЛЬКО ВЫБРАНА КАТЕГОРИЯ 
            for elem in product_1:
                RESULT_LIST_ID.append(elem)
    except:
        pass
    res_end = []
    first = True            
    try:
        res
    except:
        for index in range(len(ex_list)):
            try:
                if first:
                    first = False
                    res_end.extend(list(set(ex_list[index]) & set(ex_list[index+1])))
                if first == False:
                    res = list(set(res_end[::-1]) & set(ex_list[index+1]))
                    print(res)
                    first = True
                if res == []:
                    break
            except:
                pass
    c = 0
    
    
    if last_step == True and str(list_product[-2]) == "<QuerySet []>":
        while True:
            c+=1
            if str(list_product[-2-c]) != "<QuerySet []>":
                res =list(set(list_product[-2-c]) & set(RESULT_LIST_ID))
                break

    try:  
        result = []
        for elem in res:
            if int(elem.price) <= int(ID_BUDJET):
                result.append(elem)
        line = (len(result)//4+1)
        if len(result) % 4 == 0:
            line = line -1
        cart_product_form = CartAddProductsForm(pquant=1)
        category_camera = {" ": ""}
        category_camera_spec = {" ": ""}
        category_matrix_format = {" ": ""}
        category_Bayonet = {" ": ""}
        category_Color = {" ": ""}
        for i in Camera.objects.all():
            category_camera[i.category]= ""
            category_camera_spec[i.firm] = ""
            category_matrix_format[i.Matrix_format] = ""
            category_Bayonet[i.Bayonet] = ""
            category_Color[i.color] = ""
        
        if result == []:
            result = True
        content = {"Camers":result, 
               "line": 426* line,
               "FORM_TO_BACKET":cart_product_form,
               "category_camera": category_camera.keys(),
               "category_camera_spec": category_camera_spec.keys(), 
               "category_matrix_format": category_matrix_format.keys(),
               "category_Bayonet": category_Bayonet.keys(),
               "category_Color": category_Color.keys()
               }
        if CONTENT_FLAG == True:
            content['some_flag'] = True
            CONTENT_FLAG = False
        return render(request, "Main/URLS_FILTRED/Camera_filtred.html", content )
    except:
        result = []
        for elem in RESULT_LIST_ID:
            if int(elem.price) <= int(ID_BUDJET):
                result.append(elem)
        line = (len(result)//4+1)
        if len(result) % 4 == 0:
            line = line -1
        cart_product_form = CartAddProductsForm(pquant=1)
        category_camera = {" ": ""}
        category_camera_spec = {" ": ""}
        category_matrix_format = {" ": ""}
        category_Bayonet = {" ": ""}
        category_Color = {" ": ""}
        for i in Camera.objects.all():
            category_camera[i.category]= ""

project_site/SnapBox/Main/templates/Main/base.html
{% load static %}


<html>

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
       
        <title> Quickclick </title>
        <link rel ="stylesheet" type="text/css" href= "{% static "Main/css/base.css" %}?ver=117"> 
    </head>
    <body>
        <div id = "wrapper">
            <!-- Начало шабки сайта -->
            <div  id "header">
                <div id = "head-line">
                    <div class = "wrapp-head-line">
                        <div class = "logo">
                        </div>
                        <div class = "site-label">
                        </div>
                        <div class = "info-contact">
                            <h5> Address 1: London Wall Street 23 </h5>
                            <h5> Address 2: London Boughton Rd 95 Street </h5>
                        </div>
                        <div class = "info-contact-2" >
                            <h5> From Mon to Fri from 10:00 to 22:00 </h5>
                            <h5> Contact details: +000-00-000-0000 </h5>
                        </div>

                        <div class = "logo-phone" >
                        </div>
                        <div class = "logo-telegram" >
                        </div>
                        <div class = "logo-facebook" >
                        </div>
                    </div>
                </div>
                <div id = "head-menu">
                    <div class = "wrapp-head-menu" >
                        <div class = "navigation">
                            <ul class = "top-menu">

                                <li><a href="{% url "Main:Main"%}">
                                    
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                
                                    Home</a></li>


                                <li><a href="{% url "Main:Camers"%}">
                                
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                

                                    Cameras</a></li>

                                <li><a href="{% url "Main:Lens"%}">
                                    
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                
                                    Lenses</a></li>

                                <li><a href="{% url "Main:Tripods"%}">
                                    
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                
                                    Tripods</a></li>
                                <li><a href="{% url "Main:Lightings"%}">
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                
                                    
                                    Lighting</a></li>
                                
                                <li><a href="{% url "Main:binoculars"%}">
                                    
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                
                                    Binoculars</a></li>

                                <li class = "last"><a href="#">
                                    <span class = "button__line button__line--top"></span>
                                    <span class = "button__line button__line--right"></span>
                                    <span class = "button__line button__line--bottom"></span>
                                    <span class = "button__line button__line--left"></span>
                                    
                                    About us</a></li>
                            </ul>
                            <div class = "search">  
                                <input type = "text" value ="Search" name= "form-search" class = "search-form"/>

                            </div> 
                        
                        </div>
                    </div>
                </div>
            
            <!-- Конец шабки сайта -->

            <div class = "all_wrap">
                <div id = "right-sidebar"> <!-- Начало контента-->
                    <div class = "main-block">
                        
                        <div class ="block-content-top">
                            
                        </div>
                        <div class ="block-content-center">
                            {% block content %}
                            {% endblock content%}
                            
                        </div>
                        <div class ="block-content-botton">
                            
                        </div>
                    </div>
                </div>  <!-- Конец контента-->
                
                <div id = "left-sidebar"> <!-- Начало окна меню -->
                    <div class = "main-menu"   >
                        
                        <div class = "user-login" >
                            {% block login_logout %}
                            {%if user.is_authenticated%}
                                <div class = "block-menu-user" >
                                    <h1 >Welcome, {{user.username}} </h1>
                                    <ul class = "menu-user">
                                        <button class = "log-button-acc-2"><a href="{% url "Cart:cart_detail" %}">Basket</a></button>
                                        <button class = "log-button-acc-2"><a href="#">Settings </a></button>
                                        <button class = "log-button-acc-2"><a href="#">Support </a></button>
                                        <button class = "log-button-acc-2"><a href="#">Coupons</a></button> 
                                        <button class = "log-button-acc-2"><a href="#">Coupons</a></button> 

                                        <button class = "log-button-acc-2"><a href = "{% url "Main:logout" %}"> Logout</a></button>
                                    </ul>
                                </div>
                                
                                
                            {% else %}
                                
                                <h1>User Login</h1>
                                <h2>Username:</h2>
                                <input type = "text" placeholder="Username" id = "u-form" onkeypress= "handleKeyPress(event)" class = "user-form"/>
                                <h2>Password:</h2>
                                <input type = "password" placeholder="Password" id = "p-form" onkeypress= "handleKeyPress(event)" class = "password-form"/>                                
                                <h2>Forgot password?</h2>



                                <button class = "log-button-acc" onClick="submit()">Login</button>
                                
                                <script>
                                    function submit(){
                                        var a = document.getElementById("u-form").value;
                                        var b = document.getElementById("p-form").value;
                                        
                                        window.location.href = "{% url 'Main:authentication' %}" + "?login="+ a +"&password=" + b; 
                                    }
                                </script>
                                
                                <script>
                                    function handleKeyPress(e){
                                        var key=e.keyCode || e.which;
                                         if (key === 13){ // Клавиша Enter
                                            
                                            var a = document.getElementById("u-form").value;
                                            var b = document.getElementById("p-form").value;
                                            
                                            window.location.href = "{% url 'Main:authentication' %}" + "?login="+ a +"&password=" + b; 
                                        
                                            
                                         }
                                       }
                                </script>

                                <button class = "reg-button-acc"><a href="{% url "users:register"%}">Registration</a></button>
                                
                                
                                
                                
                                



                            {%endif%}
                            {% endblock login_logout %}
                        </div>
                            
                        <div class ="block-menu">
                            
                            {% block left-content-ctg %}
                            <div class= "label-categ-head">
                                <h1>Category</h1>
                            </div>
                            {% endblock left-content-ctg %}
                            
                        </div>
                            
                        
                        <div class = "useful-link" ></div>
                    </div>
                </div>  <!-- Конец окна меню -->
            </div>
            </div>  
        
        
        </div>


    </body>
    <div id = "popup" class= "popup">
        <a href="#header" class = "popup__area" ></a>
        <div class ="popup__body">
            <div class = "popup__content">
                <a href="#header" class= "popup__close">X</a>
                <div class= "popup__tite"> Invalid login or password! </div>
                <div class= "popup__text">
                    Please check the correctness of the entered data. You may have made mistakes such as: 
                </div>
                <div class= "popup__text">
                    <ul class = "list-invalid-password">
                        <li>
                            CAPS button is pressed
                        </li>
                        
                        <li>
                            Another language is set
                        </li>
                        <li>
                            Your device is not connected to the network
                        </li>
                    </ul>
                </div>
                

            </div>

        </div>
    </div>

    <div id = "popup-2" class= "popup">
        <a href="#header" class = "popup__area" ></a>
        <div class ="popup__body">
            <div class = "popup__content">
                <a href="#header" class= "popup__close">X</a>
                <div class= "popup__tite"> You are not registered! </div>
                <div class= "popup__text">
                    Please register and then add the product to the cart
                </div>
                
                

            </div>

        </div>
    </div>



    
</html>